### ISSUE TITLE
npm ERR! 404 Not Found: kvision-bootstrap@1.0.0

### ISSUE THREAD

**Issue by MahmoodAliL** [rjaros/kvision-examples#11]
**When I download the template build field with this?**

> Task :npm-install
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-bootstrap <<===>> G:\App Code\Web-Journey\kvision get-start\temp
late\build\node_modules_imported\kvision-bootstrap
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-select <<===>> G:\App Code\Web-Journey\kvision get-start\templat
e\build\node_modules_imported\kvision-select
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-datetime <<===>> G:\App Code\Web-Journey\kvision get-start\templ
ate\build\node_modules_imported\kvision-datetime
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-spinner <<===>> G:\App Code\Web-Journey\kvision get-start\templa
te\build\node_modules_imported\kvision-spinner
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-richtext <<===>> G:\App Code\Web-Journey\kvision get-start\templ
ate\build\node_modules_imported\kvision-richtext
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-upload <<===>> G:\App Code\Web-Journey\kvision get-start\templat
e\build\node_modules_imported\kvision-upload
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-handlebars <<===>> G:\App Code\Web-Journey\kvision get-start\tem
plate\build\node_modules_imported\kvision-handlebars
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-i18n <<===>> G:\App Code\Web-Journey\kvision get-start\template\
build\node_modules_imported\kvision-i18n
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-datacontainer <<===>> G:\App Code\Web-Journey\kvision get-start\
template\build\node_modules_imported\kvision-datacontainer
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-dialog <<===>> G:\App Code\Web-Journey\kvision get-start\templat
e\build\node_modules_imported\kvision-dialog
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-tabulator <<===>> G:\App Code\Web-Journey\kvision get-start\temp
late\build\node_modules_imported\kvision-tabulator
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-redux <<===>> G:\App Code\Web-Journey\kvision get-start\template
\build\node_modules_imported\kvision-redux
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-chart <<===>> G:\App Code\Web-Journey\kvision get-start\template
\build\node_modules_imported\kvision-chart
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-pace <<===>> G:\App Code\Web-Journey\kvision get-start\template\
build\node_modules_imported\kvision-pace
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision-moment <<===>> G:\App Code\Web-Journey\kvision get-start\templat
e\build\node_modules_imported\kvision-moment
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kvision <<===>> G:\App Code\Web-Journey\kvision get-start\template\build
\node_modules_imported\kvision
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlin-redux <<===>> G:\App Code\Web-Journey\kvision get-start\template\
build\node_modules_imported\kotlin-redux
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlinx-serialization-kotlinx-serialization-runtime <<===>> G:\App Code\
Web-Journey\kvision get-start\template\build\node_modules_imported\kotlinx-serialization-kotlinx-serialization-runtime
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\navigo-kotlin <<===>> G:\App Code\Web-Journey\kvision get-start\template
\build\node_modules_imported\navigo-kotlin
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\jquery-kotlin <<===>> G:\App Code\Web-Journey\kvision get-start\template
\build\node_modules_imported\jquery-kotlin
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlinx-coroutines-core <<===>> G:\App Code\Web-Journey\kvision get-star
t\template\build\node_modules_imported\kotlinx-coroutines-core
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlin-extensions <<===>> G:\App Code\Web-Journey\kvision get-start\temp
late\build\node_modules_imported\kotlin-extensions
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlin <<===>> G:\App Code\Web-Journey\kvision get-start\template\build\
node_modules_imported\kotlin
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\snabbdom-kotlin <<===>> G:\App Code\Web-Journey\kvision get-start\templa
te\build\node_modules_imported\snabbdom-kotlin
Junction created for G:\App Code\Web-Journey\kvision get-start\template\build\node_modules\kotlin-test <<===>> G:\App Code\Web-Journey\kvision get-start\template\b
uild\node_modules_imported\kotlin-test
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! code E404
npm ERR! 404 Not Found: kvision-bootstrap@1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mahmo\AppData\Roaming\npm-cache\_logs\2019-09-28T10_35_55_134Z-debug.log

> Task :npm-install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm-install'.
> npm install failed (exit code = 1)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
3 actionable tasks: 3 executed

**Comment by rjaros** [comment]
Take a look at #5
Are you sure  "G:\App Code\Web-Journey\kvision get-start\template\" is a local directory and not some kind of a network folder?

**Comment by MahmoodAliL** [comment]
Yes it on my local machine

**Comment by rjaros** [comment]
Could you post `C:\Users\mahmo\AppData\Roaming\npm-cache_logs\2019-09-28T10_35_55_134Z-debug.log` file?

**Comment by MahmoodAliL** [comment]
Yes

[2019-09-28T10_35_55_134Z-debug.log](https://github.com/rjaros/kvision-examples/files/3667619/2019-09-28T10_35_55_134Z-debug.log)

**Comment by rjaros** [comment]
Unfortunately it's not very helpful. But could you check, if you have some symlinks from build/node_modules/ to directories in build/node_modules_imported folder? Perhaps there is some problem creating symlinks on your system (it could be a permission problem).

**Comment by rjaros** [comment]
I'm closing this bug, as it is no longer valid (new plugin uses different tools).
