### ISSUE TITLE
Address book - fullstack ktor

### ISSUE THREAD

**Issue by SchweinchenFuntik** [rjaros/kvision-examples#12]
ERROR Application - Unhandled: POST - /kv/routeAddressServiceManager0
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.ktor.http.Parameters` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (InputStreamReader); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)

**Comment by rjaros** [comment]
It's a Ktor issue I've reported almost a year ago: https://github.com/ktorio/ktor/issues/926
Unfortunately no fix yet. Please vote for this issue! :-)
