### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by pihme** [rjaros/kvision-examples#13]
I cloned the examples and wanted to try them out. Unfortunately the builds fail.

I tried building `template-fullstack-jooby` and `addressbook-fullstack-jooby`. Both fail when executing `gradew jar`.

I do not have NodeJS installed. Also the documentation at https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up claims that NodeJS would be installed by Gradle.

Java is OpneJDK 11.0.2

```
> gradlew jar

> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :frontendProcessResources FAILED
Converted messages-en.po to messages-en.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontendProcessResources'.
> A problem occurred starting process 'command 'node''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
7 actionable tasks: 3 executed, 4 up-to-date
```

**Comment by pihme** [comment]
Did work after installing NodeJS

**Comment by rjaros** [comment]
It should be downloaded but honestly I've never tested it :-)

**Comment by rjaros** [comment]
Also note `addressbook-fullstack-jooby` application is broken at the moment because of https://github.com/jooby-project/jooby/issues/1548

**Comment by rjaros** [comment]
I've repaired building apps without NodeJS installed. External NodeJS is no longer necessary and no longer used.
