### ISSUE TITLE
Logging defaults on full-stack ktor example explicitly filter out error messages

### ISSUE THREAD

**Issue by cuchaz** [rjaros/kvision-examples#14]
This bit of the [`logback.xml`](https://github.com/rjaros/kvision-examples/blob/master/template-fullstack-ktor/src/backendMain/resources/logback.xml) file has the effect of explicitly filtering out errors from the logs.
```
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>INFO</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
```
It also filters out warnings too. That doesn't seem like a sensible default. Maybe it should be changed to allow info, warn, and error by default?

**Comment by rjaros** [comment]
Hello
You are probably right. This configuration file was contributed and I personally don't use Ktor very often, so I don't know what configuration would be optimal. Please write what you think would be best for the template project, a I'll make the changes.

**Comment by cuchaz** [comment]
Logging in Java is a bit of a mess now, with all the different libraries that talk to each other, but logging itself should be fairly independent of the libraries/frameworks that are using it, like Ktor and KVision. So the good news is we don't have to be Ktor experts to configure the logging. I'm not much of a Ktor expert either. =)

It looks like [Ktor uses SLF4J as the logging API](https://ktor.io/servers/logging.html). The KVision example/template for Ktor uses [Logback](http://logback.qos.ch/manual/configuration.html) to configure/implement SLF4J logging. I haven't looked at the examples/templates for the other backends yet, but they could be using similar solutions for logging too.

In my case, I just removed the `<filter>` element from the config entirely and that seemed to work for me. But if someone wanted more fine-grained control than that, [here's the docs on filtering in Logback](http://logback.qos.ch/manual/filters.html).

**Comment by rjaros** [comment]
Fixed in all Ktor examples.
