### ISSUE TITLE
Addressbook fullstack ktor example - hot reload support?

### ISSUE THREAD

**Issue by kam1sh** [rjaros/kvision-examples#15]
Hi! Firstly, thank you for KVision. I've readed about it on r/Kotlin, and right now I want to try it in one in-game community web-site and its admin UI.

I'm using **addressbook-fullstack-ktor** as the reference point, but when I'm using **frontendRun** task I don't see how page changes after I change the code in frontendMain.

I've readed about [Hot Module Replacement](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/hot-module-replacement) in documentation, but when I overrided `start(state: Map<String, Any>)` nothing's changed, I still need to re-run frontendRun task.

So, is it possible to include hot reload in KVision ktor example? Or it's just I don't understand HMR concepts?

**Comment by rjaros** [comment]
You should run `frontendRun` task with `-t` option:
```
./gradlew -t frontendRun
```

**Comment by kam1sh** [comment]
Forgot it. Thank you for fast response =)
