### ISSUE TITLE
ktor fullstack example broken with ktor 1.4.2

### ISSUE THREAD

**Issue by milgner** [rjaros/kvision-examples#17]
Using the ktor fullstack example, the ping service request on the backend fails with the error described in https://youtrack.jetbrains.com/issue/KTOR-1286

After downgrading to 1.4.1, it works as expected. Having just started looking into KVision a few minutes ago, I have no idea where the problem might be, though :sweat_smile:

**Comment by rjaros** [comment]
I'm aware of the problem. Ktor integration in KVision uses Jackson, so we are directly affected by KTOR-1286 regression and there is no way to workaround the issue.
Please use KVision 3.16.2 or downgrade Ktor manually to 1.4.1.

From my information, Ktor 1.4.3 should be released in about a week (~ 30 Nov).

**Comment by rjaros** [comment]
For now, I've downgraded Ktor to 1.4.1 in 3.17.0.
