### ISSUE TITLE
Use rootProject in NodeJsRootPlugin.apply(rootProject)

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision-examples#18]
When integrating the sample projects in own projects (as sub project), there are strange error messges ("check failed").
This can be fixed by calling `NodeJsRootPlugin.apply(rootProject)` with the rootProject instead of the project.

While it works for the examples, some users might be surprised when using the templates in their own hierarchy.

**Comment by rjaros** [comment]
It definitely should be fixed in all the examples.

**Comment by jschneider** [comment]
https://github.com/rjaros/kvision-examples/pull/21
