### ISSUE TITLE
Compile Error in tests (ktor fullstack example)

### ISSUE THREAD

**Issue by jschneider** [rjaros/kvision-examples#19]
When checking out the example and running "./gradlew build" I get these compile errors:

```
e: /tmp/a/kvision-examples/template-fullstack-ktor/src/frontendTest/kotlin/test/com/example/AppSpec.kt: (3, 28): Unresolved reference: test
e: /tmp/a/kvision-examples/template-fullstack-ktor/src/frontendTest/kotlin/test/com/example/AppSpec.kt: (7, 17): Unresolved reference: SimpleSpec
```

It seems the class "pl.treksoft.kvision.test.SimpleSpec" can not be found (missing dependency?)

**Comment by rjaros** [comment]
Thanks for noticing. Test dependency is incorrectly declared. It should be:

`implementation("pl.treksoft:kvision-testutils:$kvisionVersion")`

instead of

`implementation("pl.treksoft:kvision-testutils:$kvisionVersion:tests")`

**Comment by jschneider** [comment]
https://github.com/rjaros/kvision-examples/pull/21
