### ISSUE TITLE
gradlew -t run on windows, BUILD FAILED: Execution failed for task ':npm-install'. > npm install failed (exit code = 1)

### ISSUE THREAD

**Issue by NovaLogicDev** [rjaros/kvision-examples#2]
This is a known bug with windows and the Node Gradle Plugin, I haven't been able to find a workaround, and it makes all the samples unusable.

Any Help or a fix would be appreciated, thanks.

[gradle-node-plugin issue #87](https://github.com/srs/gradle-node-plugin/issues/87)
[jhipster #3053](https://github.com/jhipster/generator-jhipster/issues/3053)

**Comment by joerg-rade** [comment]
Hi,

have a look at your .npmrc, especially at:

proxy=http://<host>:<port>/
https-proxy=http://<host>:<port>/
registry=https://registry.npmjs.org/

When you don’t have/need a proxy you may need to comment it out.

HTH
-j



Kühne + Nagel (AG & Co.) KG
Rechtsform: Kommanditgesellschaft, Bremen HRA 21928, USt-IdNr.: DE 812773878.
Geschäftsleitung Kühne + Nagel (AG & Co.) KG: Dr. Hansjörg Rodi (Vors. ), Tom Ban, Martin Brinkmann, Holger Ketz, Jan-Hendrik Köstergarten, Nicholas Minde, Lars Wedel, Matthias Weiner.
Persönlich haftende Gesellschafterin: Kühne & Nagel A.G., Rechtsform: Aktiengesellschaft nach luxemburgischem Recht, HR-Nr.: B 18745, Geschäftsführendes Verwaltungsratsmitglied: Karl Gernandt.
Geschäftsleitung Region Zentral- und Osteuropa: Dr. Hansjörg Rodi (Vors.), Tom Ban, Dominic Edmonds, Thierry Held, Uwe Hött, Richard Huhn, Holger Ketz, Jan-Hendrik Köstergarten, Jan Kunze.

Wir arbeiten ausschließlich auf Grundlage der Allgemeinen Deutschen Spediteurbedingungen 2017 (ADSp 2017). Hinweis: Die ADSp 2017 weichen in Ziffer 23 hinsichtlich des Haftungshöchstbetrages für Güterschäden (§ 431 HGB) vom Gesetz ab, indem sie die Haftung bei multimodalen Transporten unter Einschluss einer Seebeförderung und bei unbekanntem Schadenort auf 2 SZR/kg und im Übrigen die Regelhaftung von 8,33 SZR/kg zusätzlich auf 1,25 Millionen Euro je Schadenfall sowie 2,5 Millionen Euro je Schadenereignis, mindestens aber 2 SZR/kg, beschränken. Die ADSp sind auf unserer Webseite als Download erhältlich. Auf Anfrage senden wir Ihnen diese auch gerne zu.

**Comment by NovaLogicDev** [comment]
Hi,

Thanks for the suggestion, but I can't find a .npmrc in either my global node installation or the local project file. After building and failing, one did appear in the build folder, but it did not contain those lines.

Thanks

**Comment by rjaros** [comment]
Hi,

I'm not using Windows very often, but I've just tried building a "showcase" example on my VirtualBox Windows 10 machine, and I've had no serious problems with this. I've just had to:
- download and install JDK
- download and install NodeJS with NPM
- download and install git
- add git paths (C:\Program Files\Git\usr\bin, C:\Program Files\Git\mingw64\bin and C:\Program Files\Git\mingw64\libexec\git-core) to system Path environment variable

Can you try this?

**Comment by NovaLogicDev** [comment]
Hello, 

I tried your suggestion on my main development system, and it didn't work. I went ahead and created a VM of windows10 and tried again which did yield success. So probably the issue is being caused by some sort of confliction with one of my other dev environments, luckily I keep a WSL Command line for just these occasions.

Thanks for the help.
