### ISSUE TITLE
Gradle continuous run don't work in most of the examples

### ISSUE THREAD

**Issue by RavMazurek** [rjaros/kvision-examples#28]
Steps:
1.Download examples
2.Open one of them
3.Run with ./gradlew -t run

Some of them works like intended - desktop or mini-template runs for me without problem/

In comparison with - addressbook-fullstack-spring-boot/addressbook-fullstack-ktor/template-fullstack-ktor I get this:
`Task 'run' not found in root project 'template-fullstack-ktor'.`

**Comment by rjaros** [comment]
For fullstack projects you need to use different task name - `frontendRun`. 
Check: https://kvision.gitbook.io/kvision-guide/6.-full-stack-development-guide/setting-up-1

**Comment by RavMazurek** [comment]
Ah, I don't know how I missed this - works like a charm now, thanks
