### ISSUE TITLE
[template-fullstack-javalin] connection refused

### ISSUE THREAD

**Issue by mdu39170** [rjaros/kvision-examples#32]
Hi,

When i start 'template-fullstack-javalin' project, i get this message : 

`<e> [webpack-dev-server] [HPM] Error occurred while proxying request 192.168.1.34:3000/kv/routePingServiceManager0 to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
`

can you help me ?

thanks

**Comment by rjaros** [comment]
Have you started both the frontend (jsRun) and the backend (jvmRun)?

**Comment by mdu39170** [comment]
that's it ! I thought it was 2 different launch options. Thanks
